### ISSUE TITLE
اطلاعات تاریخ رو چه جوری بگیرم؟

### ISSUE THREAD

**Issue by myjtag** [ARahimiQuant/finpy-tse#11]
سلام
ممنون بابت به اشتراک گذاری این لایبری شگفت انگیز، تازه پیداش کردم و دارم باهاش کار می کنم، یه تست ساده زدم

`
import finpy_tse as fpy

price = fpy.Get_Price_History(
    stock='تاپیکو',
    start_date='1402-11-01',
    end_date='1402-11-26',
    ignore_date=False,
    adjust_price=False,
    show_weekday=False,
    double_date=False)

print(price.to_string(index=False))
`
خروجی این بود به عنوان نمونه
![Screenshot 2024-02-15 133743](https://github.com/ARahimiQuant/finpy-tse/assets/17095881/f94cfe2e-8de3-4d25-8eaf-7e418180c3b7)

توی توضیحات نوشتین که تاریخ رو هم داره داده ها، اما جدول ارائه شده توی این مثال فقط ,این ها رو داره، اطلاعات تاریخ توش نیست، اطلاعات تاریخ رو چه جور میشه توی لیست داشت؟ پیشنهاد می کنم که تاریخ شمسی، میلادی و utc رو اضافه کنید.

همون کد رو با تغییر متغییر ها به صورت زیر

`
import finpy_tse as fpy

price = fpy.Get_Price_History(
    stock='تاپیکو',
    start_date='1402-11-01',
    end_date='1402-11-26',
    ignore_date=True,
    adjust_price=True,
    show_weekday=True,
    double_date=True)

print(price.to_string(index=False))
`
![Screenshot 2024-02-15 140354](https://github.com/ARahimiQuant/finpy-tse/assets/17095881/4889fa6a-d20a-4c1a-8a77-c44b05500f69)

از روز اول داده ها رو میاره، در صورتی که من بازه یک هفته ای خواستم؛، ضمنا تاریخ شمسی هم نداره
ممنون

**Comment by pooyanzarif** [comment]
ممنون بابت این لایبرری عالی! من میخوام اطلاعات سهام رو در دیتابیس خود هر روز آپدیت کنم. بنابراین دنبال تابعی میگردم که بجای اینکه اطلاعات تمام شرکتها رو یک به یک درخواست کند. اطلاعات همه شرکتها در یک روز را از سایت درخواست کند.

**Comment by ARahimiQuant** [comment]
> سلام ممنون بابت به اشتراک گذاری این لایبری شگفت انگیز، تازه پیداش کردم و دارم باهاش کار می کنم، یه تست ساده زدم
> 
> ` import finpy_tse as fpy
> 
> price = fpy.Get_Price_History( stock='تاپیکو', start_date='1402-11-01', end_date='1402-11-26', ignore_date=False, adjust_price=False, show_weekday=False, double_date=False)
> 
> print(price.to_string(index=False)) ` خروجی این بود به عنوان نمونه ![Screenshot 2024-02-15 133743](https://private-user-images.githubusercontent.com/17095881/305032754-f94cfe2e-8de3-4d25-8eaf-7e418180c3b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NzU1MDksIm5iZiI6MTcxMjQ3NTIwOSwicGF0aCI6Ii8xNzA5NTg4MS8zMDUwMzI3NTQtZjk0Y2ZlMmUtOGRlMy00ZDI1LThlYWYtN2U0MTgxODBjM2I3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA3MzMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwMGZhYTYxNTllNzYxOGJmMjU1MGE2OTllNTYzZTAzMmE1N2QxOTE4YjI2YTg4YjJiZDIzYWQ5Y2VmZjEzZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uSychTxCvLIhwzvckimJifbaUnsXxX4VtQCstLBou9o)
> 
> توی توضیحات نوشتین که تاریخ رو هم داره داده ها، اما جدول ارائه شده توی این مثال فقط ,این ها رو داره، اطلاعات تاریخ توش نیست، اطلاعات تاریخ رو چه جور میشه توی لیست داشت؟ پیشنهاد می کنم که تاریخ شمسی، میلادی و utc رو اضافه کنید.
> 
> همون کد رو با تغییر متغییر ها به صورت زیر
> 
> ` import finpy_tse as fpy
> 
> price = fpy.Get_Price_History( stock='تاپیکو', start_date='1402-11-01', end_date='1402-11-26', ignore_date=True, adjust_price=True, show_weekday=True, double_date=True)
> 
> print(price.to_string(index=False)) ` ![Screenshot 2024-02-15 140354](https://private-user-images.githubusercontent.com/17095881/305040410-4889fa6a-d20a-4c1a-8a77-c44b05500f69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NzU1MDksIm5iZiI6MTcxMjQ3NTIwOSwicGF0aCI6Ii8xNzA5NTg4MS8zMDUwNDA0MTAtNDg4OWZhNmEtZDIwYS00YzFhLThhNzctYzQ0YjA1NTAwZjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA3MzMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NGM5MzBiNDMyYjg4OGZkNTkyNzYzOWI3ODdjNzMwNmRmOWFmYjY1YjIzYmIwYTY2ODcyMDhjZGMzMTU2YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._q06d6-u0uaPd3aNloBkE57RUnzc7BHemWZg3Cj49BE)
> 
> از روز اول داده ها رو میاره، در صورتی که من بازه یک هفته ای خواستم؛، ضمنا تاریخ شمسی هم نداره ممنون

سلام، 

در خصوص نحوه استفاده از توابع به ریپوی راهنما مراجعه کنید.
https://github.com/ARahimiQuant/finpy-tse-example-notebook
 تاریخ شمسی در ایندکس دیتا فریم هست. هر بازه ای رو میتونید تاریخ بدید به تابع و فقط همون بازه رو دیتاش رو بگیرید. ضمن اینکه خروجی دیتا فریم این امکان رو بهتون میده که خودتون هم خروجی رو بر اساس تاریخ فیلتر کنید.

**Comment by ARahimiQuant** [comment]
> ممنون بابت این لایبرری عالی! من میخوام اطلاعات سهام رو در دیتابیس خود هر روز آپدیت کنم. بنابراین دنبال تابعی میگردم که بجای اینکه اطلاعات تمام شرکتها رو یک به یک درخواست کند. اطلاعات همه شرکتها در یک روز را از سایت درخواست کند.

نوتبوک راهنما رو ملاحظه بفرمایید به جواب سوالتون میرسید:
https://github.com/ARahimiQuant/finpy-tse-example-notebook
