### ISSUE TITLE
گرفتن اطلاعات تمام شرکتها در یک روز در یک درخواست

### ISSUE THREAD

**Issue by pooyanzarif** [ARahimiQuant/finpy-tse#12]
ممنون بابت این لایبرری عالی! من میخوام اطلاعات سهام رو در دیتابیس خود هر روز آپدیت کنم. بنابراین دنبال تابعی میگردم که بجای اینکه اطلاعات تمام شرکتها رو یک به یک درخواست کند. اطلاعات همه شرکتها در یک روز را از سایت درخواست کند.

**Comment by ARahimiQuant** [comment]
نوتبوک راهنما رو ببینید برای جواب سوالتون:
https://github.com/ARahimiQuant/finpy-tse-example-notebook
