### ISSUE TITLE
error when using Get_RI_History function 

### ISSUE THREAD

**Issue by mahan100** [ARahimiQuant/finpy-tse#14]
error occurs when using Get_RI_History function however other function works properly 

fpy.Get_RI_History(
    stock='خودرو',
    start_date='1400-01-01',
    end_date='1401-01-01',
    ignore_date=False,
    show_weekday=False,
    double_date=False,
    alt=False)
    
    ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[5], line 1
----> 1 fpy.Get_RI_History(
      2     stock='داوه',
      3     start_date='1400-01-01',
      4     end_date='1401-01-01',
      5     ignore_date=False,
      6     show_weekday=False,
      7     double_date=False,
      8     alt=False)

File ~/.conda/envs/tf/lib/python3.9/site-packages/finpy_tse/__init__.py:659, in Get_RI_History(stock, start_date, end_date, ignore_date, show_weekday, double_date, alt)
    657 df_RI_tab = df_RI_tab.reset_index()
    658 # determining week days:
--> 659 df_RI_tab['Weekday']=df_RI_tab['Date'].dt.weekday
    660 df_RI_tab['Weekday'] = df_RI_tab['Weekday'].apply(lambda x: calendar.day_name[x])
    661 df_RI_tab['J-Date']=df_RI_tab['Date'].apply(lambda x: str(jdatetime.date.fromgregorian(date=x.date())))

File ~/.conda/envs/tf/lib/python3.9/site-packages/pandas/core/generic.py:6299, in NDFrame.__getattr__(self, name)
   6292 if (
   6293     name not in self._internal_names_set
   6294     and name not in self._metadata
   6295     and name not in self._accessors
   6296     and self._info_axis._can_hold_identifiers_and_holds_name(name)
...
    640 elif isinstance(data.dtype, PeriodDtype):
    641     return PeriodProperties(data, orig)
--> 643 raise AttributeError("Can only use .dt accessor with datetimelike values")

AttributeError: Can only use .dt accessor with datetimelike values

**Comment by MortezaKheiri** [comment]
Use ****"get_ri_history"**** 
rather than "Get_RI_History".
![image](https://github.com/user-attachments/assets/3073d386-14d4-4f37-adaf-9661727f5c51)

**Comment by ARahimiQuant** [comment]
> Use **"get_ri_history"** rather than "Get_RI_History". ![image](https://private-user-images.githubusercontent.com/106186845/358442640-3073d386-14d4-4f37-adaf-9661727f5c51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5Mjc5NDksIm5iZiI6MTcyOTkyNzY0OSwicGF0aCI6Ii8xMDYxODY4NDUvMzU4NDQyNjQwLTMwNzNkMzg2LTE0ZDQtNGYzNy1hZGFmLTk2NjE3MjdmNWM1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQwNzI3MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NmMzM2E1ZDM4NzA5ZWUzNjE1YTYyNjUwYzg4MWMwZGU0NjBkZDYxODYzOTIyMTBhNTk4Yzc1NDU4YjA0NTZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-bU7gHIrZUXhVXEbUDgcwFCtdnQRt8SeNlQErpHY5Hk)

Thanks Morteza!
