### ISSUE TITLE
Proposal: Refactor codebase to follow Python best practices and improve maintainability

### ISSUE THREAD

**Issue by Pedram-Parsian** [ARahimiQuant/finpy-tse#15]
First, thank you for creating this useful library. I've noticed that developers often end up copying and modifying this code directly in their projects rather than using it as a dependency, likely due to its current structure and style. This pattern reduces community contributions and slows down the library's growth potential. By making the codebase more Pythonic and maintainable, we could encourage proper package usage and foster more community involvement.

I'd like to propose some structural and style improvements to make the codebase more Pythonic and maintainable.

Current Observations:
1. Code organization: Most code is in a single __init__ file, which makes maintenance and testing more difficult
2. Naming conventions: Mixed usage of double underscores (e.g., `__Check_JDate_Validity__`) which should be reserved for name mangling
3. Function parameters: Inconsistent type hints and documentation styles
4. Error handling: Direct print statements instead of proper exception handling
5. Code duplication: Similar functionality in `get_tse_webid` and `__Get_TSE_WebID__`

Proposed Improvements:
1. Restructure the project into logical modules
2. Follow PEP 8 naming conventions
3. Improve error handling
4. Add proper type hints and docstrings:
5. Reduce code duplication:

Important Note on Backward Compatibility:
These proposed changes would likely break backward compatibility with existing code. While this is a significant consideration, it might be worth considering a major version bump (e.g., v2.0.0) to implement these improvements. This would allow:
- Existing users to stay on the current version if needed
- New users to benefit from the improved structure
- Clear documentation of breaking changes
- Following semantic versioning principles

I'm happy to contribute these changes through a series of PRs if you're interested. Let me know if you'd like me to proceed with any specific part first.

**Comment by ARahimiQuant** [comment]
Thank you for your feedback!

We completely acknowledge the validity of all your critiques and suggestions. In fact, we identified these flaws earlier and rewrote the code about a year ago. However, due to some reasons, the updated version hasn’t been made public yet.

If you’re open to contributing, we’d love to collaborate. Please feel free to reach out to me directly at a.rahimi.aut@gmail.com, and we can discuss how to incorporate your thoughts into the new codebase and release it as soon as possible.
