### ISSUE TITLE
Get_RI_History function error

### ISSUE THREAD

**Issue by mahan100** [ARahimiQuant/finpy-tse#16]
df_RI_tab = fpy.Get_RI_History(
    stock='خودرو',
    start_date='1400-01-01',
    end_date='1401-01-01',
    ignore_date=False,
    show_weekday=False,
    double_date=False,
    alt=False
)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[5], line 6
      3 import jdatetime
      5 # Fetch the data using fpy.Get_RI_History
----> 6 df_RI_tab = fpy.Get_RI_History(
      7     stock='خودرو',
      8     start_date='1400-01-01',
      9     end_date='1401-01-01',
     10     ignore_date=False,
     11     show_weekday=False,
     12     double_date=False,
     13     alt=False
     14 )
     16 # Check the data type of the 'Date' column
     17 print(df_RI_tab['Date'].dtype)  # This will show the current data type of the 'Date' column

File /opt/anaconda3/envs/tf-gpu/lib/python3.9/site-packages/finpy_tse/__init__.py:659, in Get_RI_History(stock, start_date, end_date, ignore_date, show_weekday, double_date, alt)
    657 df_RI_tab = df_RI_tab.reset_index()
    658 # determining week days:
--> 659 df_RI_tab['Weekday']=df_RI_tab['Date'].dt.weekday
    660 df_RI_tab['Weekday'] = df_RI_tab['Weekday'].apply(lambda x: calendar.day_name[x])
    661 df_RI_tab['J-Date']=df_RI_tab['Date'].apply(lambda x: str(jdatetime.date.fromgregorian(date=x.date())))

File /opt/anaconda3/envs/tf-gpu/lib/python3.9/site-packages/pandas/core/generic.py:6299, in NDFrame.__getattr__(self, name)
   6292 if (
   6293     name not in self._internal_names_set
   6294     and name not in self._metadata
   6295     and name not in self._accessors
   6296     and self._info_axis._can_hold_identifiers_and_holds_name(name)
   6297 ):
   6298     return self[name]
-> 6299 return object.__getattribute__(self, name)

File /opt/anaconda3/envs/tf-gpu/lib/python3.9/site-packages/pandas/core/accessor.py:224, in CachedAccessor.__get__(self, obj, cls)
    221 if obj is None:
    222     # we're accessing the attribute of the class, i.e., Dataset.geo
    223     return self._accessor
--> 224 accessor_obj = self._accessor(obj)
    225 # Replace the property with the accessor object. Inspired by:
    226 # https://www.pydanny.com/cached-property.html
    227 # We need to use object.__setattr__ because we overwrite __setattr__ on
    228 # NDFrame
    229 object.__setattr__(obj, self._name, accessor_obj)

File /opt/anaconda3/envs/tf-gpu/lib/python3.9/site-packages/pandas/core/indexes/accessors.py:643, in CombinedDatetimelikeProperties.__new__(cls, data)
    640 elif isinstance(data.dtype, PeriodDtype):
    641     return PeriodProperties(data, orig)
--> 643 raise AttributeError("Can only use .dt accessor with datetimelike values")

AttributeError: Can only use .dt accessor with datetimelike values

**Comment by ARahimiQuant** [comment]
try alt=True!

**Comment by mahan100** [comment]
thanks 😊👍
