### ISSUE TITLE
دریافت معاملات میان روز با داده های غیرواقعی

### ISSUE THREAD

**Issue by mahan100** [ARahimiQuant/finpy-tse#18]
درود
هنگام دریافت معاملات میان روز (Price) داده های غیرواقعی رو ایجاد میکنه
![IMG_20241221_201445.png](https://github.com/user-attachments/assets/1acec943-0b68-4b84-a9ba-c0df654f64c9)

**Comment by ARahimiQuant** [comment]
با سلام،

پکیج هیچ گونه دخل و تصرفی در داده ها ندارد! در صورت مشاهده داده های پرت، ریز معاملات را از طریق سایت بررسی فرمایید.
