### ISSUE TITLE
دریافت دیتا

### ISSUE THREAD

**Issue by mostafahn** [ARahimiQuant/finpy-tse#6]
سلام
تابع Get_IntradayTrades_History
مشکل داره در هر بار فراخوانی دیتاهای متفاوت نشون میده

`fpy.Get_IntradayTrades_History(stock='درازی', start_date='1390-01-01', end_date='1402-02-01', jalali_date=True, combined_datatime=False, show_progress=True)`

**Comment by ARahimiQuant** [comment]
سلام،

داده های نمایش داده شده توسط تابع از سایت TSE دریافت میشن و تابع اقدام به خلق داده و یا دخل و تصرف در اونها نمیکنه. بنابراین اگر در فراخوانی های مختلف با دیتای متفاوتی مواجه هستید، ریشه اش پاسخی هست که TSE در فراخوانی های مختلف برمیگردونه.

**Comment by mostafahn** [comment]
کدی که شما نوشتی اینجوری برمیگردونه دیتا tse کاملا درسته چون زمان لازم برای لود شدن تمام دیتا بهش ندادین قبل اینکه کامل فچ بشه میره بازه روز بعدی..

**Comment by ARahimiQuant** [comment]
زمان لازم برای لود شدن مربوط به کرال کردن با سلنیوم (مبتنی بر بروزر) هست که تجربه اش مشابه با بازدید از صفحات وبه. اینجا، دریافت داده بر مبنای ارسال ریکوئست هست و برای ریکوئست یا دیتا دریافت میشه به طور کامل و یا نمیشه و چیزی تحت عنوان زمان بدیم لود بشه نداریم!

با این حال اگر فکر میکنید میشه با زمان دادن برای لود شدن دیتا، موضوعی که مطرح کردید رو برطرف کرد، راه حل تون رو پیشنهاد بدید یا حداقل برای نیاز خودتون پیاده سازی کنید اش!
