### ISSUE TITLE
دریافت صورت مالی نماد

### ISSUE THREAD

**Issue by masumeh-karami** [ARahimiQuant/finpy-tse#8]
سلام و سپاس از کار قشنگتون. لطفا راهنمایی کنید که چطور بر پایه کار شما میشه اطلاعات صورت مالی نماد مثل حقوق صاحبان سهام و سود و زیان یک نماد در پایان یک سال مالی رو استخراج کرد.

**Comment by ARahimiQuant** [comment]
با سلام،

محدوده فینپای، سایت TSE و داده های موجود در اون هست و شامل صورتهای مالی و سایر اطلاعات و داده هایی که در سایت کدال منتشر میشن، نمیشه. شما میتونید اطلاعات مد نظرتون رو از سایت کدال با استفاده از روش های وبکاوی (web scraping) و پکیج های مربوطه پایتون مثل requests و beautiful soup استخراج کنید. البته پکیج های دیگری هم هستند ولی ما در فینپای از این دو پکیج در عمده موارد استفاده کردیم. کمی هم باید در مورد ساختار صفحات وب اطلاعات داشته باشید تا بتونید کدهایی برای دریافت این اطلاعات نوشته و ازش استفاده کنید. خلاقیت در طراحی توابعی که خودشون بتونن در سایت کدال برای سهم و داده خاصی سرچ کنند هم میتونه انعطاف بیشتری به کدهاتون بده.
